###########################################################
#                                                         #
# Copyright (c)                                           #
#                                                         #
# The Verifiable & Control-Theoretic Robotics (VECTR) Lab #
# University of California, Los Angeles                   #
#                                                         #
# Authors: Kenny J. Chen, Ryan Nemiroff, Brett T. Lopez   #
# Contact: {kennyjchen, ryguyn, btlopez}@ucla.edu         #
#                                                         #
###########################################################

/**:
  ros__parameters:
    use_sim_time: true
    frames/odom: odom
    frames/baselink: base_link
    frames/lidar: lidar
    frames/imu: imu

    map/waitUntilMove: false
    map/dense/filtered: false
    map/sparse/leafSize: 0.5

    odom/gravity: 9.80665
    odom/computeTimeOffset: true

    odom/imu/approximateGravity: false
    odom/imu/calibration/gyro: true
    odom/imu/calibration/accel: true
    odom/imu/calibration/time: 3.0
    odom/imu/bufferSize: 5000

    odom/preprocessing/cropBoxFilter/size: 1.0
    odom/preprocessing/voxelFilter/res: 0.25

    odom/keyframe/threshD: 1.0
    odom/keyframe/threshR: 45.0

    odom/submap/keyframe/knn: 10
    odom/submap/keyframe/kcv: 10
    odom/submap/keyframe/kcc: 10
    odom/gicp/minNumPoints: 64
    odom/gicp/kCorrespondences: 16
    odom/gicp/maxCorrespondenceDistance: 0.5
    odom/gicp/maxIterations: 32
    odom/gicp/transformationEpsilon: 0.01
    odom/gicp/rotationEpsilon: 0.01
    odom/gicp/initLambdaFactor: 1e-9

    # Publishing pose covariance and GICP failure handling
    odom/publishPoseCovariance: true
    odom/gicp/failure/condMax: 1.0e7
    odom/gicp/failure/minEig: 1.0e-8
    odom/gicp/failure/fitnessPerPointMax: 1.0
    odom/gicp/failure/minInliers: 200
    odom/gicp/ignoreBadAlignment: false

    # EKF fusion controls
    odom/ekf/enable: false
    odom/ekf/useGICPCovariance: true
    odom/ekf/measurement/nis_threshold: 12.592
    odom/ekf/process/q_pos: 1.0e-3
    odom/ekf/process/q_vel: 1.0e-2
    odom/ekf/process/q_ori: 1.0e-4
    odom/ekf/process/q_bg:  1.0e-6
    odom/ekf/process/q_ba:  1.0e-6
    # IMU noise parameters (std dev)
    odom/ekf/process/noise_gyro: 1.7e-4
    odom/ekf/process/noise_accel: 2.0e-3
    odom/ekf/process/noise_gyro_bias: 1.0e-5
    odom/ekf/process/noise_accel_bias: 1.0e-4
    odom/ekf/measurement/r_pos_floor: 1.0e-4
    odom/ekf/measurement/r_ori_floor: 1.0e-4

    odom/geo/Kp: 4.5
    odom/geo/Kv: 11.25
    odom/geo/Kq: 4.0
    odom/geo/Kab: 2.25
    odom/geo/Kgb: 1.0
    odom/geo/abias_max: 5.0
    odom/geo/gbias_max: 0.5
    odom/verbose: true
    odom/keyframe/maxNum: 50
